-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.autorizacoes_vendas (
  id integer NOT NULL DEFAULT nextval('autorizacoes_vendas_id_seq'::regclass),
  imovel_id integer NOT NULL,
  created_by_user_id integer NOT NULL,
  prazo_exclusividade integer DEFAULT 0,
  comissao_percentual numeric DEFAULT 6.00,
  status character varying DEFAULT 'rascunho'::character varying CHECK (status::text = ANY (ARRAY['rascunho'::character varying, 'aguardando_assinatura'::character varying, 'assinado'::character varying, 'cancelado'::character varying, 'encerrado'::character varying]::text[])),
  clicksign_document_key character varying UNIQUE,
  clicksign_status character varying,
  clicksign_request_signature_key character varying,
  pdf_url text,
  pdf_filename character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  signed_at timestamp without time zone,
  expires_at timestamp without time zone,
  CONSTRAINT autorizacoes_vendas_pkey PRIMARY KEY (id),
  CONSTRAINT autorizacoes_vendas_imovel_id_fkey FOREIGN KEY (imovel_id) REFERENCES public.imoveis(id),
  CONSTRAINT autorizacoes_vendas_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.empresas (
  id integer NOT NULL DEFAULT nextval('empresas_id_seq'::regclass),
  created_by_user_id integer NOT NULL,
  bitrix_company_id integer UNIQUE,
  tipo character varying NOT NULL CHECK (tipo::text = ANY (ARRAY['PF'::character varying, 'PJ'::character varying]::text[])),
  nome character varying,
  cpf character varying UNIQUE,
  rg character varying,
  profissao character varying,
  estado_civil character varying,
  regime_casamento character varying,
  endereco text,
  email character varying,
  telefone character varying,
  conjuge_nome character varying,
  conjuge_cpf character varying,
  conjuge_rg character varying,
  conjuge_profissao character varying,
  conjuge_email character varying,
  razao_social character varying,
  cnpj character varying UNIQUE,
  inscricao_estadual character varying,
  inscricao_municipal character varying,
  endereco_sede text,
  rep_legal_nome character varying,
  rep_legal_cpf character varying,
  rep_legal_cargo character varying,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  last_synced_to_bitrix timestamp without time zone,
  CONSTRAINT empresas_pkey PRIMARY KEY (id),
  CONSTRAINT empresas_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.imoveis (
  id integer NOT NULL DEFAULT nextval('imoveis_id_seq'::regclass),
  empresa_id integer NOT NULL,
  created_by_user_id integer NOT NULL,
  bitrix_deal_id integer UNIQUE,
  descricao text NOT NULL,
  endereco text NOT NULL,
  matricula character varying,
  valor numeric NOT NULL,
  admin_condominio character varying,
  valor_condominio numeric,
  chamada_capital character varying,
  num_parcelas integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  last_synced_to_bitrix timestamp without time zone,
  CONSTRAINT imoveis_pkey PRIMARY KEY (id),
  CONSTRAINT imoveis_empresa_id_fkey FOREIGN KEY (empresa_id) REFERENCES public.empresas(id),
  CONSTRAINT imoveis_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  email character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  name character varying,
  role character varying DEFAULT 'broker'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'broker'::character varying]::text[])),
  bitrix_user_id integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);